#!/bin/bash
#
cmake_args+=( "-DCMAKE_BUILD_TYPE=RELEASE" )
cmake_args+=( "-DBUILD_OPAL_UNIT_TESTS=TRUE" )

# Local Variables:
# mode:sh-mode
# sh-basic-offset: 8
# indent-tabs-mode: nil
# require-final-newline: nil
# End:
