#!/bin/bash
#
# defauilt configuration for OPAL master

#..............................................................................
# arguments passed to CMake
#
cmake_args+=( "-DCMAKE_BUILD_TYPE=RELEASE" )
#cmake_args+=( "-DCMAKE_BUILD_TYPE=DEBUG" )
cmake_args+=( "-DBUILD_OPAL_UNIT_TESTS=TRUE" )
cmake_args+=( "-DENABLE_SAAMG_SOLVER=TRUE" )

#..............................................................................
# arguments passed to OPAL
#opal_args+=(...)

#..............................................................................
# arguments passed to OPAL unit tests
#unittests_args+=( '--gtest_filter=-GreenWakeFunctionTest.TestApply:Field.PeriodicBC' )

#..............................................................................
# modules to load/setup build environment
#

# Local Variables:
# mode:sh-mode
# sh-basic-offset: 8
# indent-tabs-mode: nil
# require-final-newline: nil
# End:
