#!/bin/bash
#
declare __mydir="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#
# configuration for macOS 
#
branch='master'

source "${__mydir}/default-${branch}.conf"

unittests_args+=( '--gtest_filter=-TestApply:Field.PeriodicBC' )

# Local Variables:
# mode:sh-mode
# sh-basic-offset: 8
# indent-tabs-mode: nil
# require-final-newline: nil
# End:
