#!/bin/bash
#
# configuration for running at PSI 
#

#..............................................................................
# Set the to be used branches.
# If 'regtests_branch is not defined, use the same of the source branch.
branch='master'
# regtests_branch=

#..............................................................................
# arguments passed to CMake
#
cmake_args+=( "-DCMAKE_BUILD_TYPE=RELEASE" )
cmake_args+=( "-DBUILD_OPAL_UNIT_TESTS=TRUE" )
cmake_args+=( "-DENABLE_IPPLTESTS=TRUE" )
cmake_args+=( "-DENABLE_AMR=TRUE" )
cmake_args+=( "-DENABLE_AMR_MG_SOLVER=TRUE" )
cmake_args+=( "-DENABLE_SAAMG_SOLVER=TRUE" )
cmake_args+=( "-DENABLE_BANDRF=TRUE" )
cmake_args+=( "-DENABLE_OPAL_FEL=TRUE" )

#..............................................................................
# arguments passed to OPAL
# opal_args=()

#..............................................................................
# arguments passed to OPAL unit tests
# unittests_args=()

#..............................................................................
# setup build environment
#
source /opt/psi/config/profile.bash
module purge
module use unstable
module load /afs/psi.ch/project/amas/modulefiles/toolchains/gcc-10.3.0-openmpi-4.0.5-hdf5-1.10.7
module load Python/3.6.3
module load gnuplot/5.4.0
module load emacs/26.3

# Local Variables:
# mode:sh-mode
# sh-basic-offset: 8
# indent-tabs-mode: nil
# require-final-newline: nil
# End:
