#!/bin/bash
#
declare __mydir="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#
# configuration for macOS 
#
branch='master'

#..............................................................................
# setup build environment
#
source /opt/psi/config/profile.bash
module purge
module use unstable
module load cmake/3.14.0
module load gnuplot/5.2.7
module load Python/3.6.3

module load gcc/7.4.0
module load gsl/2.6
module load OpenBLAS/0.3.7
module load gtest/1.8.1

module load openmpi/3.1.4
module load amrex/18.07_3d
module load boost/1.70.0
module load hdf5/1.10.5

module load H5hut/2.0.0rc6
module load trilinos/12.12.1

# Local Variables:
# mode:sh-mode
# sh-basic-offset: 8
# indent-tabs-mode: nil
# require-final-newline: nil
# End:
