#!/bin/bash
#
# Compile OPAL and run unit- and regression tests.
#
# Usually this script is called via CRON or a CD/CI pipeline without any
# argument.
#
# You can call this script from the command line anyway. The only excepted
# option is '--publish-dir' to override the default publish directory. If
# you use '--publish-dir=', publishing is disabled.
#
# If you don't want to run all tests, the name of the tests can be passed
# as arguments.

usage() {
        echo "
Usage:
     $()basename $0) [--publish-dir=[DIR]] [REGRESSION_TESTS]
" 1>&2
        exit 1
}

#-----------------------------------------------------------------------------
# configuration
#
# the following configuration settings must be defined here:
# - the branch to test
# - arguments to CMake
# - optional: arguments to OPAL
# - the modules to be loaded

#..............................................................................
# branch to use (same for source and regression-tests)
#
declare -r branch='master'

#..............................................................................
# arguments passed to CMake
#
declare -a cmake_args=()
#cmake_args+=( "-DCMAKE_BUILD_TYPE=RELEASE" )
cmake_args+=( "-DCMAKE_BUILD_TYPE=DEBUG" )
cmake_args+=( "-DBUILD_OPAL_UNIT_TESTS=TRUE" )
cmake_args+=( "-DENABLE_SAAMG_SOLVER=TRUE" )

#..............................................................................
# arguments passed to OPAL
declare -a opal_args=()
#opal_args+=(...)

#..............................................................................
# arguments passed to OPAL unit tests
declare unittests_args=()
unittests_args+=( '--gtest_filter=-GreenWakeFunctionTest.TestApply:Field.PeriodicBC' )

#..............................................................................
# modules to load/setup build environment
#

#
# end of configuration
#-----------------------------------------------------------------------------

#-----------------------------------------------------------------------------
# no changes should be required below this line!
#

#..............................................................................
# base directories to publish result. Final target directories are:
#
# results of regression-tests:
#	${publish_dir}/regressionTests/${branch}
# results of unit-tests:
#	${publish_dir}/unitTests/${branch} 	results of regression-tests
#
declare    publish_dir='/afs/psi.ch/project/amas/webhosting/opal'
declare -a opts=()
declare -a tests=()

while (( $# > 0 )); do
        case $1 in
                --publish-dir|--publish-dir=* )
                        if [[ $1 == *=* ]]; then
                                publish_dir="${1#*=}"
                        else
                                publish_dir=$2; shift
                        fi
                        ;;
                --force|-f|--reg-tests|--unit-tests )
                        opts+=( "$1" )
                        ;;
                -* )
                        echo "Invalid option -- $1\n"
                        usage
                        ;;
                * )
                        tests+=( "$1" )
                        ;;
        esac
        shift
done
        
#..............................................................................
# repositories for sources and regression-tests
#
declare -r src_repo_url='https://gitlab.psi.ch/OPAL/src.git'
declare -r tests_repo_url='https://gitlab.psi.ch/OPAL/regression-tests.git'

#..............................................................................
# prepend option names to CMake und OPAL arguments
#
opts+=( "${cmake_args[@]/#/--cmake-args=}" )
opts+=( "${opal_args[@]/#/--opal-args=}" )
opts+=( "${unittests_args[@]/#/--unit-tests-args=}" )

#..............................................................................
# here we go ...
#
declare -r bindir=$(dirname "$0")
"${bindir}/run-tests"				\
        --branch=${branch}                      \
        --src-repo-url="${src_repo_url}"	\
        --tests-repo-url="${tests_repo_url}"	\
        --publish-dir="${publish_dir}" 		\
        "${opts[@]}"                            \
        "${tests[@]}"

# Local Variables:
# mode:sh-mode
# sh-basic-offset: 8
# indent-tabs-mode: nil
# require-final-newline: nil
# End:
