#!/bin/bash

declare -r bindir=$(dirname "$0")

declare -r regtest_dir='/afs/psi.ch/project/amas/webhosting/opal/regressionTests'
declare -r unittest_dir='/afs/psi.ch/project/amas/webhosting/opal/unitTests'

declare -r branch='master'
declare -r repo_dir="${branch}-test"
declare -r publish_dir="${regtest_dir}/${repo_dir}"
declare -r publish_dir_unittests="${unittest_dir}/${repo_dir}"

declare -a cmake_args=()
cmake_args+=( "-DCMAKE_BUILD_TYPE=RELEASE" )
cmake_args+=( "-DBUILD_OPAL_UNIT_TESTS=TRUE" )
cmake_args+=( "-DENABLE_SAAMG_SOLVER=TRUE" )
declare -r cmake_args=( "${cmake_args[@]/#/--cmake-args=}" )

declare -a opal_args=()
declare -r opal_args=( "${opal_args[@]/#/--opal-args=}" )

module purge
module load cmake/3.10.3
module load gnuplot/5.2.7
module load Python/3.6.3

module load gcc/7.4.0
module load gsl/2.6
module load OpenBLAS/0.3.7
module load gtest/1.8.1

module load openmpi/3.1.4
module load amrex/18.07_3d
module load boost/1.70.0
module load dks/1.1.2
module load hdf5/1.10.5

module load H5hut/2.0.0rc6
module load trilinos/12.12.1


bash -x "${bindir}/run-tests"						\
		--repo-dir=${repo_dir}					\
		"${cmake_args[@]}"					\
		"${opal_args[@]}"					\
		--publish-dir="${publish_dir}" 				\
		--publish-dir-unittests="${publish_dir_unittests}"	\
		"$@"							\
		"${branch}"
