#!/usr/bin/env bash
#
# Compile OPAL and run unit- and regression tests.
#
# Usually this script is called via CRON or a CD/CI pipeline without any
# argument.
#
# You can call this script from the command line anyway. The only excepted
# option is '--publish-dir' to override the default publish directory. If
# you use '--publish-dir=', publishing is disabled.
#
# If you don't want to run all tests, the name of the tests can be passed
# as arguments.

declare -ri	EC_ARG_ERROR=1
declare -ri	EC_GIT_ERROR=10

# for Macports
# :FIXME: do we need this?
#         YES:	as long as readlink(1) shipped with Mac OS X does not
#	 	support the option '-f'
PATH+=":/opt/local/bin:/usr/local/bin"

# for Mac OS
declare -rx	MACOSX_DEPLOYMENT_TARGET=10.12

#
# default branch for OPAL sources and regression tests
declare		branch='master'
declare         regtests_branch=''

#..............................................................................
# arguments passed to CMake
#
declare -a cmake_args=()

#..............................................................................
# arguments passed to OPAL
declare -a opal_args=()

#..............................................................................
# arguments passed to OPAL unit tests
declare unittests_args=()
#
# end of configuration
#-----------------------------------------------------------------------------


#-----------------------------------------------------------------------------
# handle arguments
#

# default URL for OPAL source and regression-tests repository
declare		src_repo_url='https://gitlab.psi.ch/OPAL/src.git'
declare		tests_repo_url='https://gitlab.psi.ch/OPAL/regression-tests.git'

# run regression tests even if nothing has been changed
declare		opt_force='no'

# absolute or relative directory where to publish the results
# of the regression und unit tests. If empty, nothing will be
# published.
declare -x	publish_dir=''

# run unit- and/or regression tests
declare         opt_unittests='yes'
declare         opt_regtests='yes'

# configuration file
declare opt_config_file="default-${branch}.conf"

# tests to run, all if non passed as argument
declare -a      tests=()

while (( $# > 0 )); do
	case $1 in
                --branch|--branch=* )
                        if [[ $1 == *=* ]]; then
                                branch="${1#*=}"
                        else
                                branch="$2"; shift 1
                        fi
                        ;;
                --regtests-branch|--regtests-branch=* )
                        if [[ $1 == *=* ]]; then
                                regtests_branch="${1#*=}"
                        else
                                regtests_branch="$2"; shift 1
                        fi
                        ;;                         
		--compile )
                        opt_unittests='no'
                        opt_regtests='no'
			;;
		--cmake-args|--cmake-args=* )
                        if [[ $1 == *=* ]]; then
		                cmake_args+=( "${1#*=}" )
                        else
			        cmake_args+=( "$2" ); shift 1
		        fi
		        ;;
                --config|--config=* )
                        if [[ $1 == *=* ]]; then
		                opt_config_file="${1#*=}"
                        else
			        opt_config_file="$2"; shift 1
                        fi
                        if [[ ! -e "${opt_config_file}" ]]; then
                                echo "ERROR: configuration file does not exist - ${opt_config_file}" \
                                     1>&2
                                exit 1
                        fi
                        source "${opt_config_file}"
                        if (( $? != 0)); then
                                echo "ERROR: cannot source configuration file - ${opt_config_file} " \
                                     1>&2
                                exit 1
                        fi

                        ;;
		--opal-args|--opal-args=* )
                        if [[ $1 == *=* ]]; then
			        opal_args+=( "${1#*=}" )
                        else
			        opal_args+=( "$2" ); shift 1
                        fi
			;;
		--publish-dir|--publish-dir=* )
                        if [[ $1 == *=* ]]; then
			        publish_dir="${1#*=}"
                        else
		                publish_dir="$2"; shift 1
                        fi
                        if [[ -n ${publish_dir} ]]; then
                                publish_dir=$(readlink -f "${publish_dir}")
                        fi
		        ;;
		--src-repo-url|--src-repo-url=* )
                        if [[ $1 == *=* ]]; then
		                src_repo_url="${1#*=}"
                        else
		                src_repo_url="$2"; shift 1
                        fi
		        ;;
		--tests-repo-url|--tests-repo-url=* )
                        if [[ $1 == *=* ]]; then
		                tests_repo_url="${1#*=}"
                        else
		                tests_repo_url="$2"; shift 1
                        fi
		        ;;
                --reg-tests )
                        opt_unittests='no'
                        opt_regtests='yes'
                        ;;
                --unit-tests )
                        opt_unittests='yes'
                        opt_regtests='no'
                        ;;
                --unit-tests-args|--unit-tests-args=* )
                        if [[ $1 == *=* ]]; then
                                unittests_args+=( "${1#*=}" )
                        else
                                unittests_args+=( "$2" ); shift 1
                        fi
                        ;;
		-f | --force )
		        opt_force='yes'
		        ;;
		-* )
		        echo "Unknown option: $1" 1>&2
		        exit
		        ;;
		* )
		        tests+=( "$1" )
		        ;;
	esac
	shift 1
done

: ${regtests_branch:=${branch}}

#.............................................................................
# directory layout
#
# ${PREFIX}/scripts					${bindir}
# ${PREFIX}/workspace					${workspace}
# ${PREFIX}/workspace/OPAL-1.6				${branchdir}
# ${PREFIX}/workspace/OPAL-1.6/src			${srcdir}
# ${PREFIX}/workspace/OPAL-1.6/build			${builddir}
# ${PREFIX}/workspace/OPAL-1.6/tests			${testsbase}
# ${PREFIX}/workspace/OPAL-1.6/tests/RegressionTests	${testsdir}
# ${PREFIX}/workspace/OPAL-1.6/tests/conf		${confdir}

declare -r abs_scriptname=$(readlink -f "$0")

declare -r bindir="${abs_scriptname%/*}"
declare -r prefix="${bindir%/*}"
declare -r workspace="${prefix}/workspace"
declare -r branchdir="${workspace}/${branch}"
declare -r srcdir="${branchdir}/src"
declare    builddir="${branchdir}/build"
declare -r testsbase="${branchdir}/tests"
declare -r testsdir="${testsbase}/RegressionTests"
declare -r confdir="${testsbase}/conf"

declare -r keytab="${HOME}/.keytab"
declare -r PRINCIPAL_NAME='svcusr-amas_regr@D.PSI.CH'

declare -A result
result['compile']='-'
result['u_total']='-'
result['u_passed']='-'
result['u_failed']='-'
result['u_disabled']='-'
result['u_broken']='-'
result['r_total']='-'
result['r_passed']='-'
result['r_failed']='-'
result['r_disabled']='-'
result['r_broken']='-'

declare -r today=$(date +%Y-%m-%d)

trap _exit EXIT


_exit() {
        local -i ec=$?

        # nothing to do if publication directory is not defined or set
	# to empty string.
        [[ -n ${publish_dir} ]] || return ${ec}
	mkdir -p "${publish_dir}/${branch}"

        # org file with the table we have to update
        local -r index_org="${publish_dir}/${branch}/index.org"

        # copy template to target directory if not exist
        if [[ ! -e "${index_org}" ]]; then
	        cp -v \
                   "${bindir}/html/index.org" \
                   "${index_org}"
        fi

        # links to generated XML pages used in the table
        local -r u_results_xml="../unitTests/${branch}/results_${today}.xml"
        local -r r_results_xml="../regressionTests/${branch}/results_${today}.xml"

        # build string with result for unit-tests. This will be used as link-name.
        if [[ "${result['u_total']}" == "-" ]]; then
                local -r u_report='-'
        else
                local -r u_t="total:${result['u_total']}"
                local -r u_p="passed:${result['u_passed']}"
                local -r u_f="failed:${result['u_failed']}"
                local -r u_d="disabled:${result['u_disabled']}"
                local -r u_b="broken:${result['u_broken']}"
                local -r u_report="[[${u_results_xml}][${u_t}; ${u_p}; ${u_f}; ${u_d}; ${u_b}]]"
        fi
        # build string with result for regression-tests. This will be used as link-name.
        if [[ "${result['r_total']}" == "-" ]]; then
                local -r r_report='-'
        else
                local -r r_t="total:${result['r_total']}"
                local -r r_p="passed:${result['r_passed']}"
                local -r r_f="failed:${result['r_failed']}"
                local -r r_d="disabled:${result['r_disabled']}"
                local -r r_b="broken:${result['r_broken']}"
                local -r r_report="[[${r_results_xml}][${r_t}, ${r_p}, ${r_f}, ${r_d}, ${r_b}]]"
        fi
        # add new line to org table
        line=""
        line+="| ${today} "
        line+="| ${result['compile']} "
        line+="| ${u_report} "
        line+="| ${r_report} "
        line+="|"
        local -r tmpfile=$(mktemp "/tmp/awk.XXXXXX")
        awk "{print}; /^\|---/ {print \"${line}\"}" \
            ${index_org} > "${tmpfile}"
        mv "${tmpfile}" "${index_org}"

	emacs "${index_org}" --batch -f org-html-export-to-html --kill
}

clone_repo() {
	local -r repo_url="$1"
	local -r dir="$2"
	{
		git clone "${repo_url}" "${dir}"|| exit ${EC_GIT_ERROR}
		cd "${dir}"
		git checkout "${branch}" 	|| exit ${EC_GIT_ERROR}
	}
}

update_repo() {
	local -r repodir="$1"
	if [[ -z "${repodir}" ]]; then
		echo "$0: Missing argument!" 1>&2
		exit ${EC_ARG_ERROR}
	fi

	if [[ ! -d "${repodir}" ]]; then
		echo "${repodir}: does not exist or is not a directory!" 1>&2
		exit ${EC_ARG_ERROR}
	fi

	cd "${repodir}"

	if ! git rev-parse --is-inside-work-tree 1>/dev/null 2>&1 ; then
		echo "${repodir}: is not a Git working directory!" 1>&2
		exit 1
	fi

	local -r branch=$(git rev-parse --abbrev-ref HEAD)
	if [[ "${branch}" != "${branch}" ]]; then
		git checkout "${branch}" || exit 10
	fi
	git fetch || { echo "git fetch failed!" 1>&2; exit 10; }
	local -i num_changed_files=$(git diff --name-only  "origin/${branch}"  | wc -l | awk '{print $1}')
	if (( $num_changed_files == 0 )); then
		echo "Working directory '${repodir}' is up to date!"
		return 1
	fi
	git merge "origin/${branch}" || { echo "git merge failed!" 1>&2; exit 11; };
	return 0
}

compile_opal() {
        result['compile']='failed'
	cd "${basedir}" 	|| exit 1
	rm -rf "${builddir}"	|| exit 1
	mkdir "${builddir}"	|| exit 1
	cd "${builddir}"	|| exit 1
	cmake "${cmake_args[@]}" "${srcdir}" || exit 1
	time make -j5 || exit 1
        result['compile']='ok'
}

run_unit_test() {
        # compile with unit-tests enabled?
        local -r tests_bin="${builddir}/tests/opal_unit_tests"
        [[ -x "${tests_bin}" ]] || return 0

        # run unit-test only if OPAL has been compiled
        [[ ${result['compile']} == '-' ]] && return 0

        if [[ -n "${publish_dir}" ]]; then
                local -r publish_unittests_dirs="${publish_dir}/unitTests/${branch}"
                mkdir -p "${publish_unittests_dirs}"
                local output_file="${publish_unittests_dirs}/results_${today}.xml"
                unittests_args+=( "--gtest_output=xml:${output_file}" )
        fi

        ${tests_bin} "${unittests_args[@]}"
        local -i ec=$?

        [[ -n ${publish_dir} ]] || return ${ec}

        # add stylesheet to output
        sed -n -i 'p;1a <?xml-stylesheet type="text/xsl" href="results.xsl"?>' \
            "${output_file}" 

        local -i tests
        local -i failures
        local -i disabled
        local -i errors

        eval $(awk '/<testsuites / {printf "%s %s %s %s\n", $2, $3, $4, $5}' \
                   "${output_file}")

        test_overview="[ total: ${tests} "
        test_overview+="| failures: ${failures} "
        test_overview+="| disabled: ${disabled} "
        test_overview+="| errors: ${errors} ] <br/>"

        result['u_total']=${tests}
        result['u_passed']=$((tests - failures - disabled - errors))
        result['u_failed']=${failures}
        result['u_disabled']=${disabled}
        result['u_broken']=${errors}

        line="<a href=\"${output_file##*/}\">${today}</a> ${test_overview}"

        if [[ ! -e "${publish_unittests_dirs}/index.html" ]]; then
	        echo "<head>
  <body>
  </body>
</head>
" > "${publish_unittests_dirs}/index.html"
        fi
        if [[ ! -e "${publish_unittests_dirs}/result.xsl" ]]; then
	        cp -v \
                   "${bindir}/html/gtest-result.xsl" \
                   "${publish_unittests_dirs}/results.xsl"
        fi
        sed -i "/  <body>/a ${line}" "${publish_unittests_dirs}/index.html"
        return ${ec}
}

run_regressiontests() {
        local -r run_tests="${bindir}/run-reg-tests.py"

        local opts=()
        if [[ -n "${publish_dir}" ]]; then
                local -r publish_regtests_dir="${publish_dir}/regressionTests/${branch}"
	        mkdir -p "${publish_regtests_dir}"
	        opts+=("--publish-dir=${publish_regtests_dir}")
        fi

	if [[ -n "${opal_args}" ]]; then
		opts+=(${opal_args[@]/#/--opal-args=})
	fi
	opts+=("--opal-exe-path=${builddir}/src")
	opts+=("--base-dir=${testsdir}")
        
	"${run_tests}" "${opts[@]}" "--" "${tests[@]}"
        local -i ec=$?

        [[ -n ${publish_dir} ]] || return ${ec}

        # get results from HTML file created/updated by regression-tests 
        local index_html="${publish_regtests_dir}/index.html"
        read passed broken failed total < <(
                awk "/${today}/ {
                     split(\$3, p, \":\");
                     split(\$5, b, \":\");
                     split(\$7, f, \":\");
                     split(\$9, t,  \":\");
                     printf \"%s %s %s %s\n\", p[2], b[2], f[2], t[2]; exit}" \
                             < ${index_html})
        result['r_total']=${total/\]}
        result['r_passed']=${passed}
        result['r_failed']=${failed}
        result['r_disabled']='-'
        result['r_broken']=${broken}

        return ${ec}
}

main() {
	local -r opalbin="${builddir}/src/opal"

	#.....................................................................
	if [[ ! -d "${testsdir}" ]]; then
		echo "Cloning regression tests repository..."
		clone_repo "${tests_repo_url}" "${testsbase}"	|| exit ${EC_GIT_ERROR}
	else
		echo "Updating regression tests repository..."
		update_repo "${testsbase}"
	fi
	if [[ $? == 0 ]] || [[ ${opt_force} == 'yes' ]] ; then
		opt_force='yes'
	fi

	#.....................................................................
	if [[ ! -d "${srcdir}" ]]; then
		echo "Cloning OPAL source repository..."
		clone_repo "${src_repo_url}" "${srcdir}"	|| exit ${EC_GIT_ERROR}
	else
		echo "Updating OPAL source repository..."
		update_repo "${srcdir}"
	fi
	if [[ $? == 0 ]] || [[ ! -e "${opalbin}" ]]; then
		echo "Compiling OPAL ..."
		compile_opal || exit 1
		opt_force='yes'
	fi
	if [[ ${opt_unittests} == 'no' ]] && [[ ${opt_regtests} == 'no' ]]; then
		echo "Compiling OPAL done ..."
		return 0
	fi

	[[ ${opt_force} == 'no' ]] && return 0
	if [[ -r "${keytab}" ]]; then
		declare -rx KRB5CCNAME=$(mktemp /tmp/krb5cc_$(id -u)_XXXXXX)
		/usr/bin/kinit -t "${keytab}" -k "${PRINCIPAL_NAME}"	|| exit 2
		/usr/bin/aklog						|| exit 2
	fi
        if [[ ${opt_unittests} == 'yes' ]]; then
		echo "Running unit tests..."
		run_unit_test
        fi
        if [[ ${opt_regtests} == 'yes' ]]; then
		echo "Running regression tests..."
		run_regressiontests || return 1
        fi
	if [[ -r "${keytab}" ]]; then
		/usr/bin/unlog
		/usr/bin/kdestroy
	fi
}

main

# Local Variables:
# mode:sh-mode
# sh-basic-offset: 8
# indent-tabs-mode: nil
# require-final-newline: nil
# End:
