#!/bin/bash

declare -ri	EC_ARG_ERROR=1
declare -ri	EC_GIT_ERROR=10

# for Macports
# :FIXME: do we need this?
#         YES:	as long as readlink(1) shipped with Mac OS X does not
#	 	support the option '-f'
PATH+=":/opt/local/bin:/usr/local/bin"

# for Mac OS
declare -rx	MACOSX_DEPLOYMENT_TARGET=10.12

#-----------------------------------------------------------------------------
# handle arguments
#

# default URL for OPAL source and regression-tests repository
declare		src_repo_url='https://gitlab.psi.ch/OPAL/src.git'
declare		tests_repo_url='https://gitlab.psi.ch/OPAL/regression-tests.git'

# run regression tests even if nothing has been changed
declare		arg_force_run='no'

# default branch for OPAL sources and regression tests
declare		arg_branch='master'

# compile only
declare		arg_compile_only='no'

# absolute or relative directory where to publish the results
# of the regression tests. If empty, nothing will be published.
declare -x	publish_dir=''

# absolute or relative directory where to publish the results
# of the unit tests. If empty, nothing will be published.
declare 	publish_dir_unittests=''

# relative  directory where to clone the Git source repository
# if empty and 'publish_dir' is specified, use base-name of it
# if neither is specified, use name of branch (which defaults
# to master)
declare -x	repo_dir=''

# arguments passed to CMake
declare -a	cmake_args=()

# arguments passed to OPAL
declare -a	opal_args=()

# arguments passed to the regression test runner
declare	-a opts=()

while (( $# > 0 )); do
	case $1 in
		--compile-only )
			arg_compile_only='yes'
			;;
		--cmake-args )
			cmake_args+=( $2 )
			shift 1
			;;
		--cmake-args=* )
			cmake_args+=( ${1#*=} )
			;;
		--opal-args )
			opal_args+=("$2")
			shift 1
			;;
		--opal-args=* )
			opal_args+=("${1#*=}")
			;;
		--publish-dir )
			publish_dir="$2"
			shift 1
			;;
		--publish-dir=* )
			publish_dir="${1#*=}"
			;;
		--publish-dir-unittests )
			publish_dir_unittests="$2"
			shift 1
			;;
		--publish-dir-unittests=* )
			publish_dir_unittests="${1#*=}"
			;;
		--repo-dir )
			repo_dir="$2"
			shift 1
			;;
		--repo-dir=* )
			repo_dir="${1#*=}"
			;;
		--src-repo-url )
			src_repo_url="$2"
			shift 1
			;;
		--src-repo-url=* )
			src_repo_url="${1#*=}"
			;;
		--tests-repo-url )
			tests_repo_url="$2"
			shift 1
			;;
		--tests-repo-url=* )
			tests_repo_url="${1#*=}"
			;;
		-f | --force )
			arg_force_run='yes'
			;;
		-* )
			echo "Unknown option: $1" 1>&2
			exit
			;;
		* )
			arg_branch="$1"
			;;
	esac
	shift 1
done

if [[ -z "${repo_dir}" ]]; then
	repo_dir=${arg_branch}
fi

#.............................................................................
# directory layout
#
# ${PREFIX}/scripts					${bindir}
# ${PREFIX}/workspace					${workspace}
# ${PREFIX}/workspace/OPAL-1.6				${branchdir}
# ${PREFIX}/workspace/OPAL-1.6/src			${srcdir}
# ${PREFIX}/workspace/OPAL-1.6/build			${builddir}
# ${PREFIX}/workspace/OPAL-1.6/tests			${testsbase}
# ${PREFIX}/workspace/OPAL-1.6/tests/RegressionTests	${testsdir}
# ${PREFIX}/workspace/OPAL-1.6/tests/conf		${confdir}

declare -r abs_scriptname=$(readlink -f "$0")

declare -r bindir="${abs_scriptname%/*}"
declare -r prefix="${bindir%/*}"
declare -r workspace="${prefix}/workspace"
declare -r branchdir="${workspace}/${repo_dir}"
declare -r srcdir="${branchdir}/src"
declare    builddir="${branchdir}/build"
declare -r testsbase="${branchdir}/tests"
declare -r testsdir="${testsbase}/RegressionTests"
declare -r confdir="${testsbase}/conf"

declare -r keytab="${HOME}/.keytab"
declare -r PRINCIPAL_NAME='svcusr-amas_regr@D.PSI.CH'

clone_repo() {
	local -r repo_url="$1"
	local -r dir="$2"
	{
		git clone "${repo_url}" "${dir}"|| exit ${EC_GIT_ERROR}
		cd "${dir}"
		git checkout "${arg_branch}" 	|| exit ${EC_GIT_ERROR}
	}
}

update_repo() {
	local -r repodir="$1"
	if [[ -z "${repodir}" ]]; then
		echo "$0: Missing argument!" 1>&2
		exit ${EC_ARG_ERROR}
	fi

	if [[ ! -d "${repodir}" ]]; then
		echo "${repodir}: does not exist or is not a directory!" 1>&2
		exit ${EC_ARG_ERROR}
	fi

	cd "${repodir}"

	if ! git rev-parse --is-inside-work-tree 1>/dev/null 2>&1 ; then
		echo "${repodir}: is not a Git working directory!" 1>&2
		exit 1
	fi

	local -r branch=$(git rev-parse --abbrev-ref HEAD)
	if [[ "${branch}" != "${arg_branch}" ]]; then
		git checkout "${arg_branch}" || exit 10
	fi
	git fetch || { echo "git fetch failed!" 1>&2; exit 10; }
	local -i num_changed_files=$(git diff --name-only  "origin/${arg_branch}"  | wc -l | awk '{print $1}')
	if (( $num_changed_files == 0 )); then
		echo "Working directory '${repodir}' is up to date!"
		return 1
	fi
	git merge "origin/${arg_branch}" || { echo "git merge failed!" 1>&2; exit 11; };
	return 0
}

compile_opal() {
	cd "${basedir}" 	|| exit 1
	rm -rf "${builddir}"	|| exit 1
	mkdir "${builddir}"	|| exit 1
	cd "${builddir}"	|| exit 1
	cmake "${cmake_args[@]}" "${srcdir}"
	time make -j5 || exit 1
}

run_unit_test() {
	[[ -n "${publish_dir_unittests}" ]] || return 0
	tests_bin="${builddir}/tests/opal_unit_tests"
	[[ -x "${tests_bin}" ]] || return 0

	mkdir -p "${publish_dir_unittests}"
	local today=$(date +%Y-%m-%d)
	local output_file="${publish_dir_unittests}/results_${today}".xml
	${builddir}/tests/opal_unit_tests --gtest_output=xml:"${output_file}"
	sed -n -i 'p;1a <?xml-stylesheet type="text/xsl" href="results.xsl"?>' "${output_file}" 

	local -i tests
	local -i failures
	local -i disabled
	local -i errors

	eval $(awk '/<testsuites / {printf "%s %s %s %s\n", $2, $3, $4, $5}' "${output_file}")

	test_overview="[ total: ${tests} "
	test_overview+="| failures: ${failures} "
	test_overview+="| disabled: ${disabled} "
	test_overview+="| errors: ${errors} ] <br/>"

	line="<a href=\"${output_file##*/}\">${today}</a> ${test_overview}"

	if [[ ! -e "${publish_dir_unittests}/index.html" ]]; then
		echo "<head>
  <body>
  </body>
</head>
" > "${publish_dir_unittests}/index.html"
	fi
	if [[ ! -e "${publish_dir_unittests}/result.xsl" ]]; then
		cp -v "${bindir}/html/gtest-result.xsl" "${publish_dir_unittests}/results.xsl"
	fi
	sed -i "/  <body>/a ${line}" "${publish_dir_unittests}/index.html"
}

run_regressiontests() {
	if [[ -n "${publish_dir}" ]]; then
		mkdir -p "${publish_dir}"
		opts+=("--publish-dir=${publish_dir}")
	fi
	if [[ -n "${opal_args}" ]]; then
		opts+=(${opal_args[@]/#/--opal-args=})
	fi
	opts+=("--opal-exe-path=${builddir}/src")
	opts+=("--base-dir=${testsdir}")
	"${run_tests}" "${opts[@]}" "--" "${tests[@]}"
}

main() {

	#.....................................................................
	if [[ ! -d "${testsdir}" ]]; then
		echo "Cloning regression tests repository..."
		clone_repo "${tests_repo_url}" "${testsbase}"	|| exit ${EC_GIT_ERROR}
	else
		echo "Updating regression tests repository..."
		update_repo "${testsbase}"
	fi
	if [[ $? == 0 ]] || [[ ${arg_force_run} == 'yes' ]] ; then
		arg_force_run='yes'
	fi

	# read configuration and tests to run
	if [[ ! -r "${confdir}/regression_tests.conf" ]]; then
		echo "Configuration of regression tests cannot be read!" 1>&2
		exit 2
	fi

	declare -r opalbin="${builddir}/src/opal"

	declare -r run_tests="${bindir}/run-reg-tests.py"

	#.....................................................................
	if [[ ! -d "${srcdir}" ]]; then
		echo "Cloning OPAL source repository..."
		clone_repo "${src_repo_url}" "${srcdir}"	|| exit ${EC_GIT_ERROR}
	else
		echo "Updating OPAL source repository..."
		update_repo "${srcdir}"
	fi
	if [[ $? == 0 ]] || [[ ! -e "${opalbin}" ]]; then
		echo "Compiling OPAL ..."
		compile_opal || exit 1
		arg_force_run='yes'
	fi
	if [[ "${arg_compile_only}" == 'yes' ]]; then
		echo "Compiling OPAL done ..."
		exit 0
	fi

	if [[ ${arg_force_run} == 'yes' ]] ; then
		if [[ -r "${keytab}" ]]; then
			declare -rx KRB5CCNAME=$(mktemp /tmp/krb5cc_$(id -u)_XXXXXX)
			/usr/bin/kinit -t "${keytab}" -k "${PRINCIPAL_NAME}"	|| exit 2
			/usr/bin/aklog						|| exit 2
		fi

		echo "Running unit tests..."
		run_unit_test
		echo "Running regression tests..."
		run_regressiontests || exit 1

		if [[ -r "${keytab}" ]]; then
			/usr/bin/unlog
			/usr/bin/kdestroy
		fi
	fi
}

main
