#!/bin/bash

declare -ri EC_ARG_ERROR=1
declare -ri EC_GIT_ERROR=10

# for Macports
# :FIXME: do we need this?
#         YES:	as long as readlink(1) shipped with Mac OS X does not
#	 	support the option '-f'
PATH+=":/opt/local/bin:/usr/local/bin"

# for Mac OS 
declare -rx MACOSX_DEPLOYMENT_TARGET=10.9

declare -r GIT_SERVER='gitlab.psi.ch'
declare    SRC_REPOSITORY='OPAL/src.git'
declare -r TESTS_REPOSITORY='OPAL/regression-tests.git'

#exec 1> $0.stdout
#exec 2> $0.stderr

# 
declare	arg_force_run='no'
declare arg_publish_results='yes'
declare	arg_branch='master'
declare arg_protocol='https'
declare arg_compile_only='no'
declare arg_enable_dks='no'
declare arg_use_dks='no'

declare -x REGTEST_WWW=''

# arguments passed to the regression test runner
declare	-a opts=()

while (( $# > 0 )); do
	case $1 in
		--compile-only )
			arg_compile_only='yes'
			;;
		--do-publish )
			arg_publish_results=='yes'
			;;
		--dont-publish )
			arg_publish_results=='no'
			;;
		--enable-dks )
			arg_enable_dks='yes'
			;;
		--use-dks )
			arg_enable_dks='yes'
			arg_use_dks='yes'
			opts+=( '--use-dks' )
			;;
		--protocol )
			arg_protocol="$2"
			shift 1
			;;
		--protocol=* )
			arg_protocol="${1#*=}"
			;;
		--publish-dir )
			REGTEST_WWW="$2"
			shift 1
			;;
		--publish-dir=* )
			REGTEST_WWW="${1#*=}"
			;;
		--src-repo )
			SRC_REPOSITORY="$2"
			shift 1
			;;
		--src-repo=* )
			SRC_REPOSITORY="${1#*=}"
			;;
		-f | --force )
			arg_force_run='yes'
			;;
		-* )
			echo "Unknown option: $1" 1>&2
			exit
			;;
		* )
			arg_branch="$1"
			;;
	esac
	shift 1
done

case "${arg_protocol}" in
	https | git )
		:
		;;
	* )
		echo "Protocoll for Git must be either 'https' or 'git'!" 1>&2 && exit ${EC_ARG_ERROR}
		;;
esac

if [[ "${arg_protocol}" == 'https' ]]; then
	declare fmt_g="https://%s/%s"
else
	declare fmt_g="git@%s:%s"
fi
declare -r src_repo_g=$(printf "${fmt_g}" "${GIT_SERVER}" "${SRC_REPOSITORY}")
declare -r tests_repo_g=$(printf "${fmt_g}" "${GIT_SERVER}" "${TESTS_REPOSITORY}")

if [[ ${arg_publish_results} != 'yes' ]]; then
	opts+=( "--dont-publish" )
fi

declare branch_subdir="${SRC_REPOSITORY//\//-}-${arg_branch}"
[[ "${arg_enable_dks}" == 'yes' ]] && branch_subdir+='-DKS'
[[ "${arg_enable_dks}" == 'yes' ]] && [[ "${arg_use_dks}" == 'yes' ]] && branch_subdir+='-USED'

#.............................................................................
# directory layout
#
# ${PREFIX}/scripts					${bindir}
# ${PREFIX}/workspace					${workspace}
# ${PREFIX}/workspace/OPAL-1.6				${branchdir}
# ${PREFIX}/workspace/OPAL-1.6/src			${srcdir}
# ${PREFIX}/workspace/OPAL-1.6/build			${builddir}
# ${PREFIX}/workspace/OPAL-1.6/tests			${testsbase}
# ${PREFIX}/workspace/OPAL-1.6/tests/RegressionTests	${testsdir}
# ${PREFIX}/workspace/OPAL-1.6/tests/conf		${confdir}

declare -r abs_scriptname=$(readlink -f "$0")

declare -r bindir="${abs_scriptname%/*}"
declare -r prefix="${bindir%/*}"
declare -r workspace="${prefix}/workspace"
declare -r branchdir="${workspace}/${branch_subdir}"
declare -r srcdir="${branchdir}/src"
declare    builddir="${branchdir}/build"
declare -r testsbase="${branchdir}/tests"
declare -r testsdir="${testsbase}/RegressionTests"
declare -r confdir="${testsbase}/conf"

declare -r keytab="${HOME}/.keytab"

declare -a cmake_config=()
load_cmake_config() {
	cmake_config+=( "-DCMAKE_BUILD_TYPE=RELEASE" )
	cmake_config+=( "-DENABLE_SAAMG_SOLVER=TRUE" )
	cmake_config+=( "-DBUILD_OPAL_UNIT_TESTS=TRUE" )

	if [[ "${arg_enable_dks}" == 'yes' ]]; then
		cmake_config+=( "-DENABLE_DKS=TRUE" )
	fi
	test -r "${confdir}/cmake.conf" && source "$_" || :
}

load_modules() {
	source "${confdir}/modules.conf"
}

clone_repo() {
	local -r repo_url="$1"
	local -r dir="$2"
	{
		git clone "${repo_url}" "${dir}"|| exit ${EC_GIT_ERROR}
		cd "${dir}"
		git checkout "${arg_branch}" 	|| exit ${EC_GIT_ERROR}
	}
}

update_repo() {
	local -r repodir="$1"
	if [[ -z "${repodir}" ]]; then
		echo "$0: Missing argument!" 1>&2
		exit ${EC_ARG_ERROR}
	fi

	if [[ ! -d "${repodir}" ]]; then
		echo "${repodir}: does not exist or is not a directory!" 1>&2
		exit ${EC_ARG_ERROR}
	fi

	cd "${repodir}"

	if ! git rev-parse --is-inside-work-tree 1>/dev/null 2>&1 ; then
		echo "${repodir}: is not a Git working directory!" 1>&2
		exit 1
	fi

	local -r branch=$(git rev-parse --abbrev-ref HEAD)
	if [[ "${branch}" != "${arg_branch}" ]]; then
		git checkout "${arg_branch}" || exit 10
	fi
	git fetch || { echo "git fetch failed!" 1>&2; exit 10; }
	local -i num_changed_files=$(git diff --name-only  "origin/${arg_branch}"  | wc -l | awk '{print $1}')
	if (( $num_changed_files == 0 )); then
		echo "Working directory '${repodir}' is up to date!"
		return 1
	fi
	git merge "origin/${arg_branch}" || { echo "git merge failed!" 1>&2; exit 11; };
	return 0
}

compile_opal() {
	cd "${basedir}" 	|| exit 1
	rm -rf "${builddir}"	|| exit 1
	mkdir "${builddir}"	|| exit 1
	cd "${builddir}"	|| exit 1
	load_cmake_config	|| exit 1
	cmake "${cmake_config[@]}" "${srcdir}"
	time make -j5 || exit 1
}

run_unit_test() {
	[[ -n "${UNIT_TESTS_PREFIX}" ]] || return 0
	tests_bin="${builddir}/tests/opal_unit_tests"
	[[ -x "${tests_bin}" ]] || return 0
	mkdir -p "${UNIT_TESTS_DIR}"
	local today=$(date +%Y-%m-%d)
	local output_file="${UNIT_TESTS_DIR}/results_${today}".xml
	${builddir}/tests/opal_unit_tests --gtest_output=xml:"${output_file}"
	sed -n -i 'p;1a <?xml-stylesheet type="text/xsl" href="results.xsl"?>' "${output_file}" 

	local -i tests
	local -i failures
	local -i disabled
	local -i errors

	eval $(awk '/<testsuites / {printf "%s %s %s %s\n", $2, $3, $4, $5}' "${output_file}")

	test_overview="[ total: ${tests} "
	test_overview+="| failures: ${failures} "
	test_overview+="| disabled: ${disabled} "
	test_overview+="| errors: ${errors} ] <br/>"

	line="<a href=\"${output_file##*/}\">${today}</a> ${test_overview}"

	sed -i "/  <body>/a ${line}" "${UNIT_TESTS_DIR}/index.html"
}

run_regressiontests() {
	mkdir -p "${REGTEST_WWW}"

	opts+=( "--regtests-dir=${testsdir}" )
	"${run_tests}" "${opts[@]}" "${tests[@]}"
}

main() {

	#.....................................................................
	if [[ ! -d "${testsdir}" ]]; then
		echo "Cloning regression tests repository..."
		clone_repo "${tests_repo_g}" "${testsbase}"	|| exit ${EC_GIT_ERROR}
	else
		echo "Updating regression tests repository..."
		update_repo "${testsbase}"
	fi
	if [[ $? == 0 ]] || [[ ${arg_force_run} == 'yes' ]] ; then
		arg_force_run='yes'
	fi

	# read configuration and tests to run
	if [[ ! -r "${confdir}/regression_tests.conf" ]]; then
		echo "Configuration of regression tests cannot be read!" 1>&2
		exit 2
	fi
	source "${confdir}/regression_tests.conf"

	# these shell variable are used in the tests
	declare -rx OPAL_EXE_PATH="${builddir}/src"
	declare -r opalbin="${builddir}/src/opal"

	declare -r run_tests="${bindir}/run-reg-tests.py"

	if [[ -z "${REGTEST_WWW}" ]]; then
		REGTEST_WWW="${PUBLISH_DIR}/${arg_branch}"
	fi
	UNIT_TESTS_DIR+="${UNIT_TESTS_PREFIX}/${arg_branch}"
	if [[ "${arg_enable_dks}" == 'yes' ]]; then
		REGTEST_WWW+="-DKS"
		UNIT_TESTS_DIR+="-DKS"
		if [[ "${arg_use_dks}" == 'yes' ]]; then
			REGTEST_WWW+="-USED"
			UNIT_TESTS_DIR+="-USED"
		fi
	fi

	load_modules

	#.....................................................................
	if [[ ! -d "${srcdir}" ]]; then
		echo "Cloning OPAL source repository..."
		clone_repo "${src_repo_g}" "${srcdir}"	|| exit ${EC_GIT_ERROR}
	else
		echo "Updating OPAL source repository..."
		update_repo "${srcdir}"
	fi
	if [[ $? == 0 ]] || [[ ! -e "${opalbin}" ]]; then
		echo "Compiling OPAL ..."
		compile_opal || exit 1
		arg_force_run='yes'
	fi
	if [[ "${arg_compile_only}" == 'yes' ]]; then
		echo "Compiling OPAL done ..."
		exit 0
	fi

	if [[ ${arg_force_run} == 'yes' ]] ; then
		if [[ -r "${keytab}" ]]; then
			declare -rx KRB5CCNAME=$(mktemp /tmp/krb5cc_$(id -u)_XXXXXX)
			/usr/bin/kinit -t "${keytab}" -k "${PRINCIPAL_NAME}"	|| exit 2
			/usr/bin/aklog						|| exit 2
		fi

		echo "Running unit tests..."
		run_unit_test
		echo "Running regression tests..."
		run_regressiontests || exit 1

		if [[ -r "${keytab}" ]]; then
			/usr/bin/unlog
			/usr/bin/kdestroy
		fi
	fi
}

main
